-- MySQL Script generated by MySQL Workbench
-- Sun Sep 22 19:31:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema zapping_test_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zapping_test_db` ;

-- -----------------------------------------------------
-- Schema zapping_test_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zapping_test_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `zapping_test_db` ;

-- -----------------------------------------------------
-- Table `zapping_test_db`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zapping_test_db`.`locations` ;

CREATE TABLE IF NOT EXISTS `zapping_test_db`.`locations` (
  `idlocation` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idlocation`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `zapping_test_db`.`cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zapping_test_db`.`cars` ;

CREATE TABLE IF NOT EXISTS `zapping_test_db`.`cars` (
  `idcar` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(100) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `price` DECIMAL(18,2) NULL DEFAULT NULL,
  `km` INT(11) NULL DEFAULT NULL,
  `year` INT(11) NULL DEFAULT NULL,
  `url` VARCHAR(200) NULL DEFAULT NULL,
  `idlocation` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idcar`),
  INDEX `idlocation_idx` (`idlocation` ASC) VISIBLE,
  CONSTRAINT `idlocation`
    FOREIGN KEY (`idlocation`)
    REFERENCES `zapping_test_db`.`locations` (`idlocation`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
